In [14]:
# *** Parte 1 - Normalização de Features ***
# Questão 1 (StandardScaler - sklearn):

import pandas as pd
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler

# Carrega o dataset Iris
iris = load_iris()
df_iris = pd.DataFrame(iris.data, columns=iris.feature_names)

# Exibe os dados originais
print("Dados originais:")
display(df_iris.describe())

# Aplica a normalização com StandardScaler
scaler = StandardScaler()
dados_normalizados = scaler.fit_transform(df_iris)

# Cria DataFrame com os dados escalonados
df_normalizado = pd.DataFrame(dados_normalizados, columns=df_iris.columns)

# Exibe os dados transformados
print("\nDados normalizados com StandardScaler:")
display(df_normalizado.describe())

# Calcula e exibe a média e o desvio padrão
print("\nMédia das features (esperado ≈ 0):")
print(df_normalizado.mean())

print("\nDesvio padrão das features (esperado ≈ 1):")
print(df_normalizado.std())

Dados originais:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

Dados normalizados com StandardScaler:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,1.500000e+02,1.500000e+02,1.500000e+02,1.500000e+02
mean,-1.468455e-15,-1.823726e-15,-1.610564e-15,-9.473903e-16
std,1.003350e+00,1.003350e+00,1.003350e+00,1.003350e+00
min,-1.870024e+00,-2.433947e+00,-1.567576e+00,-1.447076e+00
25%,-9.006812e-01,-5.923730e-01,-1.226552e+00,-1.183812e+00
50%,-5.250608e-02,-1.319795e-01,3.364776e-01,1.325097e-01
75%,6.745011e-01,5.586108e-01,7.627583e-01,7.906707e-01
max,2.492019e+00,3.090775e+00,1.785832e+00,1.712096e+00

Média das features (esperado ≈ 0):
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

Desvio padrão das features (esperado ≈ 1):
sepal length (cm)    1.00335
sepal width (cm)     1.00335
petal length (cm)    1.00335
petal width (cm)     1.00335
dtype: float64

In [15]:
# Questão 2 (StandardScaler manual):

import numpy as np

# Função que aplica o escalonamento padrão manual
def escalonamento_padrao_manual(dados):
    medias = np.mean(dados, axis=0)
    desvios = np.std(dados, axis=0)
    return (dados - medias) / desvios

# Aplica a função ao dataset original
dados_np = df_iris.values
dados_escalonados_manualmente = escalonamento_padrao_manual(dados_np)

# Cria DataFrame com os dados manualmente escalonados
df_manual = pd.DataFrame(dados_escalonados_manualmente, columns=df_iris.columns)

# Exibe os dados normalizados manualmente
print("Dados normalizados manualmente:")
display(df_manual.describe())

# Compara os resultados com o StandardScaler
comparacao = np.allclose(df_normalizado, df_manual, atol=1e-8)
print("\nOs resultados manuais são equivalentes ao StandardScaler?", comparacao)

Dados normalizados manualmente:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,1.500000e+02,1.500000e+02,1.500000e+02,1.500000e+02
mean,-1.468455e-15,-1.823726e-15,-1.610564e-15,-9.473903e-16
std,1.003350e+00,1.003350e+00,1.003350e+00,1.003350e+00
min,-1.870024e+00,-2.433947e+00,-1.567576e+00,-1.447076e+00
25%,-9.006812e-01,-5.923730e-01,-1.226552e+00,-1.183812e+00
50%,-5.250608e-02,-1.319795e-01,3.364776e-01,1.325097e-01
75%,6.745011e-01,5.586108e-01,7.627583e-01,7.906707e-01
max,2.492019e+00,3.090775e+00,1.785832e+00,1.712096e+00

Os resultados manuais são equivalentes ao StandardScaler? True

In [16]:
# Questão 3 (Normalização L2 - Norma Euclidiana)

from sklearn.preprocessing import Normalizer

# Aplica normalização L2 (linha com norma Euclidiana igual a 1)
normalizador_l2 = Normalizer(norm='l2')
dados_l2 = normalizador_l2.fit_transform(df_iris)

# Cria DataFrame com os dados normalizados
df_l2 = pd.DataFrame(dados_l2, columns=df_iris.columns)

print("Dados normalizados com norma L2:")
display(df_l2.head())

# Verifica a norma L2 das primeiras linhas
normas_l2 = np.linalg.norm(dados_l2, ord=2, axis=1)
print("\nNorma L2 das primeiras 5 amostras:")
print(normas_l2[:5])

Dados normalizados com norma L2:

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           0.803773          0.551609           0.220644          0.031521
1           0.828133          0.507020           0.236609          0.033801
2           0.805333          0.548312           0.222752          0.034269
3           0.800030          0.539151           0.260879          0.034784
4           0.790965          0.569495           0.221470          0.031639

Norma L2 das primeiras 5 amostras:
[1. 1. 1. 1. 1.]

In [17]:
# Questão 4 (Normalização L1 - Norma Manhattan)

# Aplica normalização L1 (linha com soma absoluta igual a 1)
normalizador_l1 = Normalizer(norm='l1')
dados_l1 = normalizador_l1.fit_transform(df_iris)

# Cria DataFrame com os dados normalizados
df_l1 = pd.DataFrame(dados_l1, columns=df_iris.columns)

print("Dados normalizados com norma L1:")
display(df_l1.head())

# Verifica a soma L1 das primeiras linhas
somas_l1 = dados_l1.sum(axis=1)
print("\nSoma L1 das primeiras 5 amostras (esperado = 1):")
print(somas_l1[:5])

Dados normalizados com norma L1:

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           0.500000          0.343137           0.137255          0.019608
1           0.515789          0.315789           0.147368          0.021053
2           0.500000          0.340426           0.138298          0.021277
3           0.489362          0.329787           0.159574          0.021277
4           0.490196          0.352941           0.137255          0.019608

Soma L1 das primeiras 5 amostras (esperado = 1):
[1. 1. 1. 1. 1.]

In [25]:
# *** Parte 2 - Seleção de Features ***
# Questão 5 (Estratégia de filtragem com Breast Cancer Dataset):

from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np

# Carrega o dataset
dados = load_breast_cancer()
X = pd.DataFrame(dados.data, columns=dados.feature_names)
y = dados.target

# Calcula a correlação de Pearson entre cada feature e a variável alvo
correlacoes = X.corrwith(pd.Series(y))

# Ordena as correlações em ordem decrescente de relevância
correlacoes_ordenadas = correlacoes.abs().sort_values(ascending=False)

# Seleciona as 10 features mais correlacionadas
top_10_features = correlacoes_ordenadas.head(10).index.tolist()
X_filtrado = X[top_10_features]

print("Top 10 features selecionadas por filtragem (correlação com o target):")
for i, feature in enumerate(top_10_features, start=1):
    print(f"{i}. {feature}")

Top 10 features selecionadas por filtragem (correlação com o target):
1. worst concave points
2. worst perimeter
3. mean concave points
4. worst radius
5. mean perimeter
6. worst area
7. mean radius
8. mean area
9. mean concavity
10. worst concavity

In [31]:
# Questão 6 (Método Wrapper (RFE)):

from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Cria modelo base
modelo = LogisticRegression(max_iter=5000)

# Aplica RFE (Recursive Feature Elimination)
rfe = RFE(estimator=modelo, n_features_to_select=10)
rfe.fit(X, y)

# Coleta as features selecionadas
features_wrapper = X.columns[rfe.support_].tolist()

print("Top 10 features selecionadas pelo método Wrapper (RFE):")
for i, feature in enumerate(features_wrapper, start=1):
    print(f"{i}. {feature}")

Top 10 features selecionadas pelo método Wrapper (RFE):
1. mean radius
2. mean compactness
3. mean concavity
4. texture error
5. worst radius
6. worst smoothness
7. worst compactness
8. worst concavity
9. worst concave points
10. worst symmetry

In [30]:
# Questão 7 (Método Embedding):

from sklearn.linear_model import LassoCV

modelo_lasso = LassoCV()
modelo_lasso.fit(X, y)

# Coleta features com coeficiente diferente de zero
features_embedding = X.columns[modelo_lasso.coef_ != 0].tolist()

print("Features selecionadas pelo método Embedding (Lasso):")
for i, feature in enumerate(features_embedding, start=1):
    print(f"{i}. {feature}")

Features selecionadas pelo método Embedding (Lasso):
1. mean area
2. worst texture
3. worst perimeter
4. worst area